name: Conventional Commits

on: [push, pull_request] # Trigger on both push and pull request events to ensure commit messages are validated in all scenarios.

jobs:
  validate-commits: # Name of the job
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4 # Use the latest version of the checkout action
        with:
          fetch-depth: 0 # Essential to fetch all history for linting

      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.4.2 # Use the latest stable version of the action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix,chore,docs,style,refactor,perf,test,ci,build" # Optional, set if you want a subset of commit types to be allowed.
