name: Conventional Commits

on: [push, pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essential to fetch all history for linting

      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix,chore,docs,style,refactor,perf,test,ci,build" # Optional, set if you want a subset of commit types to be allowed.
