name: Commit messages validation
description: Workflow to validate each commit pushed to the branch ensuring convention commits patterns.

on: [push, pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essential to fetch all history for linting

      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1
        with:
          allowed-commit-types: "feat,fix,chore,docs,style,refactor,perf,test,ci,build"
